<?php

namespace AppBundle\Repository;

/**
 * RepoRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class RepoRepository extends \Doctrine\ORM\EntityRepository
{
    public function all()
    {
        $qb = $this->createQueryBuilder('repo');
        $qb
            ->select('repo.id', 'repo.name', 'repo.fullName', 'repo.htmlUrl', 'repo.description',
                'repo.tags', 'repo.remark')
            ->where('repo.isDeleted = false')
            ->orderBy('repo.id', 'asc');

        return $qb->getQuery()->getArrayResult();
    }

    public function search($filters = [])
    {
        $qb = $this->createQueryBuilder('repo');
        $qb->select('repo.id', 'repo.name', 'repo.fullName', 'repo.htmlUrl', 'repo.description',
            'repo.tags', 'repo.remark')
            ->where('repo.isDeleted = false')
            ->orderBy('repo.id', 'asc');

        foreach ($filters as $filter) {
            if ($filter['name'] == 'name') {
                $qb
                    ->andWhere('repo.fullName LIKE :filterName')
                    ->setParameter('filterName', '%' . $filter['value'] . '%');

            }
        }

        return $qb->getQuery()->getArrayResult();
    }
}
